// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7pkSe7xons0nIlfSFMnSMf4jIXZ1Jbg',
    appId: '1:84244619870:web:96fd03a0a5ec32ac188acf',
    messagingSenderId: '84244619870',
    projectId: 'real-time-92ba3',
    authDomain: 'real-time-92ba3.firebaseapp.com',
    storageBucket: 'real-time-92ba3.appspot.com',
    measurementId: 'G-0FM83DDJQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sjUvom4938d1Reyc0mcgPacGPwxkjGw',
    appId: '1:84244619870:android:72de808d16206968188acf',
    messagingSenderId: '84244619870',
    projectId: 'real-time-92ba3',
    storageBucket: 'real-time-92ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvm_jKSFjupr3N4OJ6u9DvecjGjeP3AAA',
    appId: '1:84244619870:ios:f78b2f8c6ce0fe93188acf',
    messagingSenderId: '84244619870',
    projectId: 'real-time-92ba3',
    storageBucket: 'real-time-92ba3.appspot.com',
    iosBundleId: 'com.example.realTimeDb',
  );
}
